ann:
  url: https://www.animenewsnetwork.com
  timeout: 30000
  maxItems: 10

anilist:
  api: https://graphql.anilist.co
  authToken: ${AUTH_TOKEN}
  
spring:
  main:
    banner-mode: "off"

logging:
  level:
    root: error
    com.shinshinjiru: info
